export default {
    openTabs: {
        playingTime: false,
        suggestPlayers: false,
        reviewScore: false,
        numReviewers: false,
        complexity: false,
        numPlayers: false,
        categories: false,
        ageRange: false,
        designer: false,
        artists: false,
        publisher: false,
    },
    activeCriteria: {
        playingTime: false,
        suggestedsPlayers: false,
        reviewScore: false,
        numReviewers: false,
        complexity: false,
        numPlayers: false,
        categories: false,
        ageRange: false,
        designers: false,
        artists: false,
        publishers: false,
    },
    leftNavOpen: true,

    playingTime: [1, 240], //in minutes
    complexity: [0, 5],
    ageRange: [1, 99],
    averageReviewScore: 0,
    numberOfReviewers: 0,
    categories: [],
    designers: [],
    artists: [],
    publishers: [],
    suggestedPlayers: [1, 99],
    numberOfPlayers: [1, 99]
};
